home/urls.py
from django.conf.urls import url 
from . import views 

app_name = 'home'

urlpatterns = [
    url(r'^$', views.allNotes, name= 'all_notes'),
]

note_app/urls.py
from django.conf.urls import url 
from . import views 

app_name = 'note_app'

urlpatterns = [
    url(r'^$', views.all_notes, name= 'all_notes'),
    # url(r'^(?P<id>\d+)$', views.detail, name= 'note_detail')
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name= 'note_detail'),
     url(r'^add$', views.note_add, name= 'add_notes'),
     url(r'^(?P<slug>[-\w]+)/edit$', views.edit, name= 'edit_Notes'),
]

notes/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
       path('', include('home.urls', namespace='home')),
    path('note/', include('note_app.urls', namespace='note')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





# change subject admin panel 

admin.site.site_header = "Notes Admin Panel"
admin.site.site_title = "Notes App Admin"
admin.site.site_index_title = "Welcome To Notes App Admin Panel"

note_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# Create your models here.
class Note(models.Model):
    user    = models.ForeignKey(User, on_delete= models.CASCADE)
    title   = models.CharField(max_length=50)
    slug    = models.SlugField(null=True , blank=True)
    content = RichTextField()
    created = models.DateTimeField(blank=True, auto_now=False, auto_now_add=False, default=datetime.datetime.now)
    active  = models.BooleanField(default = True)
    tags    = models.CharField(blank=True,max_length=100)

    img     = models.ImageField( upload_to="note-img")

    def save(self, *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note , self).save(*args, **kwargs)    

    def __str__(self):
        return self.title
    

note_app/forms.py
from django import forms
from .models import Note
from ckeditor.widgets import CKEditorWidget



class NoteForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Note 
        fields = [ 'title', 'content', 'tags']

note_app/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Note 
from .forms import NoteForm
from django.contrib import messages
from accounts.models import Profile

# Create your views here.

#show all note 
def all_notes(request):
    user = request.user
    profile = get_object_or_404(Profile , user=user )
    all_notes = Note.objects.filter(user = user )
    context={
        'all_notes' : all_notes,
        'profile' : profile
    }
    return render(request, 'notes.html', context)



#show one note 
def detail(request, slug):
    note = Note.objects.get(slug=slug)
    all_notes = Note.objects.filter(user = user )
    context = {
        'note' : note,
        'profile' : profile
    }
    return render(request, 'one_notes.html', context)
    


def note_add(request):
    user = request.user
    profile = get_object_or_404(Profile , user=user )
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid:
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Profile details updated.')
            return redirect('/note')
    else:

        form = NoteForm()
    context = {
        'form' : form,
        'profile' : profile
    }
    return render(request, 'add.html', context)



def edit(request, slug):
     user = request.user
     profile = get_object_or_404(Profile , user=user )
     notes = get_object_or_404( Note,slug=slug)
     if request.method == 'POST':
        form = NoteForm(request.POST, instance=notes)
        if form.is_valid:
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'edit notes successing ')
            return redirect('/note')
     else:
        form = NoteForm(instance=notes)

     context = {
        'form' : form,
        'profile' : profile
     }
     return render(request, 'edit.html', context)

note_app/templates/add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}

<div class='container'>
 <form method='POST'>
    {% csrf_token %}
         {{ form.media }}
        {% bootstrap_form form %}


     {% buttons %}
          <button type="submit" class="btn btn-primary">Add_note</button>
    {% endbuttons %}
   
</form>


</div>
{% endblock  %}

note_app/templates/all_notes.html
{% block context %}
     <a href='{% url 'note:add_notes' %}'>add_newNote</a>
     <br>
     <hr>
    {% for note in all_notes %}
          <a href='{% url 'note:note_detail' note.slug %}'>{{note}}</a>
            <br>
    {% endfor %}
{% endblock  %}

note_app/templates/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block body %}


<div class='container'>         
<form method='POST'>
    {% csrf_token %}
   
     {{ form.media }}
    {% bootstrap_form form %}
      {% buttons %}
          <button type="submit" class="btn btn-primary">update_note</button>
    {% endbuttons %}
</form>

</div>
{% endblock  %}

note_app/templates/note_detail.html
{% block context %}
       <hr>
          <a href="{% url 'note:edit_Notes' note.slug %}">update Note</a>
         
     <br>
       <hr>
       <h1>{{note}}</h1>
       <h4>{{note.content | safe }}</h4>
       <h4>{{note.created}}</h4>
       <h4>{{note.tags}}</h4>
{% endblock  %}>

note_app/templates/notes.html
{% extends 'base.html' %}
{% load static %}
{% block  body%}
        
 <section class="ftco-section goto-here">
    	<div class="container">
    		<div class="row justify-content-center">
          <div class="col-md-12 heading-section text-center ftco-animate mb-5">
          	<span class="subheading">All Note </span>
            <h2 class="mb-2">You can create note </h2>
          </div>
        </div>
        <div class="row">
		{% for note in all_notes %}
        	<div class="col-md-4">
        		<div class="property-wrap ftco-animate">
        			<div class="img d-flex align-items-center justify-content-center" style="background-image: url(images/work-1.jpg);">
        				<div class="list-agent d-flex align-items-center">
        					<a href="#" class="agent-info d-flex align-items-center">
        						<div class="img-2 rounded-circle" style="background-image: url(images/person_1.jpg);"></div>
        						<h3 class="mb-0 ml-2">Ben Ford</h3>
        					</a>
        					<div class="tooltip-wrap d-flex">
        						<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="Bookmark">
        							<span class="ion-ios-heart"><i class="sr-only">Bookmark</i></span>
        						</a>
        						<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="Compare">
        							<span class="ion-ios-eye"><i class="sr-only">Compare</i></span>
        						</a>
        					</div>
        				</div>
        			</div>
        			<div class="text">
        				<h3 class="mb-0"><a href='{% url 'note:note_detail' note.slug %}'>{{note.title}}</a></h3>
        				<span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{note.content | safe |truncatewords:10}}</span>
					    	<span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{note.slug}}</span>
					    	<span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{note.created|date:"j M"}}</span>
					    	<span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{note.active}}</span>
        	      <span class="location d-inline-block mb-3"><i class="ion-ios-pin mr-2"></i>{{note.user.username}}</span>
        			</div>
        		</div>
        	</div>
			{% endfor %}
    </section>	

 
   
{% endblock  %}

   

note_app/templates/one_notes.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
             <section class="ftco-section goto-here">
    	<div class="container">
    		<div class="row justify-content-center">
          <div class="col-md-12 heading-section text-center ftco-animate mb-5">
          	<span class="subheading">All Note </span>
            <h2 class="mb-2">You can create note </h2>
          </div>
        </div>
        <div class="row">
        	<div class="col-md-10">
        		<div class="property-wrap ftco-animate">
        			<div class="img d-flex align-items-center justify-content-center" style="background-image: url(images/work-1.jpg);">
        				<div class="list-agent d-flex align-items-center">
        					<a href="#" class="agent-info d-flex align-items-center">
        						<div class="img-2 rounded-circle" style="background-image: url({% static 'images/person_1.jpg' %});"></div>
        						<h3 class="mb-0 ml-2">Ben Ford</h3>
        					</a>
        					<div class="tooltip-wrap d-flex">
        						<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="Bookmark">
        							<span class="ion-ios-heart"><i class="sr-only">Bookmark</i></span>
        						</a>
        						<a href="#" class="icon-2 d-flex align-items-center justify-content-center" data-toggle="tooltip" data-placement="top" title="Compare">
        							<span class="ion-ios-eye"><i class="sr-only">Compare</i></span>
        						</a>
        					</div>
        				</div>
        			</div>
        			<div class="text">
        				<h3 class="mb-0"><a href="properties-single.html">{{note.title}}</a></h3>
        				<span class="location d-inline-block mb-3"></i>{{note.content | safe }}</span>
                <br>
        			  <span class="location d-inline-block mb-3"></i>{{note.created|date:"j M"}}</span>
                 <br>
        			  <span class="location d-inline-block mb-3"></i>{{note.active}}</span>
                 <br>
        			  <span class="location d-inline-block mb-3"></i>{{note.tags}}</span>
                  <br>
        			  <span class="location d-inline-block mb-3"></i>{{note.user.username}}</span>
        			</div>
        		</div>
        	</div>
        </div>
    	</div>
    </section>	

  
{% endblock  %}
   