accounts/urls.py
from django.conf.urls import url 
from . import views 
from django.contrib.auth.views import LoginView , LogoutView

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name= 'home'),
    url(r'^login/$', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout$', LogoutView.as_view()),
    url(r'^signup/$', views.register, name='register'),

    url(r'^(?P<slug>[-\w]+)/$', views.profile , name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile , name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password , name='change_password')
]
 

home/urls.py
from django.conf.urls import url 
from . import views 

app_name = 'home'

urlpatterns = [
    url(r'^$', views.allNotes, name= 'all_notes'),
]

notes/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
       path('', include('home.urls', namespace='home')),
    path('note/', include('note_app.urls', namespace='note')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





# change subject admin panel 

admin.site.site_header = "Notes Admin Panel"
admin.site.site_title = "Notes App Admin"
admin.site.site_index_title = "Welcome To Notes App Admin Panel"

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from django.db.models.signals import post_save
from ckeditor.fields import RichTextField

# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User , on_delete = models.CASCADE)
    slug = models.SlugField(null=True , blank=True)
    headline =  models.CharField(max_length=50)
    bio =  RichTextField()
    img =  models.ImageField(upload_to='profile_img')
    join_date =  models.DateTimeField(blank=True, default = datetime.datetime.now)



    def save(self, *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(Profile , self).save(*args, **kwargs)    

    def __str__(self):
        return '%s' %(self.user)


### signals 
# 

def create_profile(sender , **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile , sender= User)        

accounts/forms.py
from django import forms 
from . import models
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta : 
        model = User 
        fields = ['first_name' , 'last_name' , 'email', 'username']

class ProfileForms(forms.ModelForm):
    class Meta :
        model = models.Profile
        fields = [ 'headline', 'bio', 'img' ]

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from django.contrib.auth import login , authenticate
from .models import Profile
from django.shortcuts import get_object_or_404
from .forms import UserForm , ProfileForms
from django.contrib import messages

# Create your views here.
def home(request):
    pass



def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid:
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username = username , password = password )
            login(request, user)
            return redirect('/note')
    else :
        form = UserCreationForm         
    context = {
        'form' : form ,
    }
    return render(request, 'signup.html', context)



def profile(request , slug):
    profile = get_object_or_404(Profile, slug=slug)
    context = {
       'profile' : profile
    }

    return render(request, 'profile.html', context)
    

def edit_profile(request , slug):
    profile =  profile = get_object_or_404(Profile, slug=slug)

    if request.method == 'POST':
        userForm = UserForm(request.POST , instance=request.user)
        profileForm = ProfileForms(request.POST, request.FILES , instance=profile)
        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
          #  new_profile =  profileForm(commit=False)
          #  new_profile.user = request.user
          #  new_profile.save()
            profileForm.save()
            messages.success(request, 'edit profiles successing ')
            return redirect('/')
    
    else: 
        userForm = UserForm(instance=request.user)
        profileForm = ProfileForms(instance=profile)

        context = {
            'userForm' : userForm,
            'profileForm' : profileForm
        }

        return render(request, 'edit_profile.html' , context )

def change_password(request, slug):
    profile =  profile = get_object_or_404(Profile, slug=slug)  

    if request.method == 'POST' :
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid() :
            password_form.save()
            
            return redirect('/')

    else : 
        password_form = PasswordChangeForm(request.user)


    context = {
        'password_form' : password_form
    }   

    return render(request, 'change_password.html' , context) 

accounts/templates/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class='container'>

<form method='post'>
   {% csrf_token %}

 
   {% bootstrap_form password_form %}

     {% buttons %}
           <button type="submit" class="btn btn-primary">change password</button>
    {% endbuttons %}
   

</form>

</div>

{% endblock  %}

accounts/templates/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class='container'>
<form method='post'>
   {% csrf_token %}

    {% bootstrap_form userForm %}
    {% bootstrap_form profileForm %}

       {% buttons %}
          
   <button type="submit" class="btn btn-primary">change save</button>
    {% endbuttons %}
   

</form>

</div>

{% endblock  %}

accounts/templates/login.html
 {% extends 'base.html' %}
 {% load bootstrap4 %}
 {% load static %}

{% block body %}

<div class='container'>
<form method='post'>
     {% csrf_token %}
     {% bootstrap_form form %}
     
     {% buttons %}
           <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
   

       
</form>
</div>

{% endblock  %}

accounts/templates/profile.html
 {% extends 'base.html' %}
 {% load static %}
 {% block  body %}
 
  <center>
   {% if profile.img %}
       <img src="{{profile.img.url}}" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
       {% else %}
         <h1>image not appeare</h1>
    {% endif %}
      <h3 class="media-heading">{{profile.user}} </h3>
                <span><strong>Skills: </strong></span>
                  <br/>
                <span class="label label-warning">HTML5/CSS</span>
                <br/>
                <span class="label label-info">Adobe CS 5.5</span>
                 <br/>
                <span class="label label-info">Microsoft Office</span>
                 <br/>
                <span class="label label-success">{{profile.bio}}</span>
                 <br/>
    </center>
      <div class = 'row'>
               <a href={% url 'accounts:edit_profile'  profile.slug%} >editProfile</a>
               <a href={% url 'accounts:change_password'  profile.slug%} >chanePassword</a>
   </div>

{% endblock  %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
 {% load static %}

{% block body %}

<div class='container'>
<form method='post'>
     {% csrf_token %}

        {% bootstrap_form form %}

    {% buttons %}
          
          <button type="submit" class="btn btn-primary">signup</button>
    {% endbuttons %}
   

     
</form>
</div>
 
{% endblock  %}