accounts/urls.py
from django.conf.urls import url 
from . import views 
from django.contrib.auth.views import LoginView , LogoutView

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name= 'home'),
    url(r'^login/$', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout$', LogoutView.as_view()),
    url(r'^signup/$', views.register, name='register'),

    url(r'^(?P<slug>[-\w]+)/$', views.profile , name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile , name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password , name='change_password')
]
 

home/urls.py
from django.conf.urls import url 
from . import views 

app_name = 'home'

urlpatterns = [
    url(r'^$', views.allNotes, name= 'all_notes'),
]

notes/urls.py
from django.contrib import admin
from django.urls import  include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
       path('', include('home.urls', namespace='home')),
    path('note/', include('note_app.urls', namespace='note')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





# change subject admin panel 

admin.site.site_header = "Notes Admin Panel"
admin.site.site_title = "Notes App Admin"
admin.site.site_index_title = "Welcome To Notes App Admin Panel"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Findstate - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'site/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'site/css/animate.css' %}">
    

	<link rel="stylesheet" href="{% static 'site/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'site/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'site/css/magnific-popup.css' %}">

	<link rel="stylesheet" href="{% static 'site/css/aos.css' %}">

	<link rel="stylesheet" href="{% static 'site/css/ionicons.min.css' %}">


	<link rel="stylesheet" href="{% static 'site/css/bootstrap-datepicker.css' %}">
	<link rel="stylesheet" href="{% static 'site/css/jquery.timepicker.css' %}">

    
	<link rel="stylesheet" href="{% static 'site/css/flaticon.css' %}">
	<link rel="stylesheet" href="{% static 'site/css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'site/css/style.css' %}">
  </head>
  <body>
    
	  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="/">Quick Notes</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
             {% if user.is_authenticated %}
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'note:all_notes' %}" class="nav-link">Your Notes</a></li>
             <li class="nav-item"><a href="{% url 'accounts:profile' profile.slug %}" class="nav-link">Profile</a></li>
	        </ul>
          {% else %}
            <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
	          <li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link">Signup</a></li>
	        </ul>
          {% endif %}
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
 {% block body %}
 {% endblock  %}  


    <footer class="ftco-footer ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Findstate</h2>
              <p>Far far away, behind the word mountains, far from the countries.</p>
              <ul class="ftco-footer-social list-unstyled mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Community</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Search Properties</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>For Agents</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Reviews</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>FAQs</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">About Us</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Our Story</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Meet the team</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Careers</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Company</h2>
              <ul class="list-unstyled">
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>About Us</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Press</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Careers</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope pr-4"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">
	
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'site/js/jquery.min.js' %}"></script>
  <script src="{% static 'site/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'site/js/popper.min.js' %}"></script>
  <script src="{% static 'site/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'site/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'site/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'site/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'site/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'site/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'site/js/aos.js' %}"></script>
  <script src="{% static 'site/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'site/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'site/js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'site/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'site/js/google-map.js' %}"></script>
  <script src="{% static 'site/js/main.js' %}"></script>
    
  </body>
</html>